#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the aVeryBigSum function below.
def aVeryBigSum(ar):
    return (sum)

if __name__ == '__main__':
    
    ar_count = int(input())

    ar = list(map(int, input().rstrip().split()))  
    sum=0
    for i in range(0,len(ar)):
        sum=sum+ar[i]
        sum= aVeryBigSum(ar)
    print(sum)


