#!/bin/python3

import math
import os
import random
import re
import sys

countA=0
countO=0

st=input().split()
s=int(st[0])
t=int(st[1])

ab=input().split()
a=int(ab[0])
b=int(ab[1])

mn=input().split()
m=int(mn[0])
n=int(mn[1])

apple = list(map(int, input().rstrip().split()))
orange = list(map(int, input().rstrip().split()))

for i in range(len(apple)):
    v=a+apple[i]
    if v in range(s,t+1):
        countA+=1
for i in range(len(orange)):
    v=b+orange[i]
    if v in range(s,t+1):
        countO+=1
print(countA)
print(countO)

        
        

