#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the kangaroo function below.
x1v1x2v2=input().split()
x1=int(x1v1x2v2[0])
v1=int(x1v1x2v2[1])
x2=int(x1v1x2v2[2])
v2=int(x1v1x2v2[3])
def kangaroo(x1, v1, x2, v2):
    if(v1==v2):
        if(x1==x2):
            return "YES"
        else:
            return "NO"
    if((x1-x2)%(v2-v1)==0 and ((x1-x2)/(v2-v1))>0):
        return "YES"
    else:
        return "NO"
    
res=kangaroo(x1, v1, x2, v2)
print(res)
    
