#!/bin/python3

import os
import sys

#
# Complete the simpleArraySum function below.
#
def simpleArraySum(ar):
    #
    return result
    #

if __name__ == '__main__':

    ar_count = int(input())

    ar = list(map(int, input().rstrip().split()))
    result=0
    for i in range(0,len(ar)):
        result=result+ar[i]
    print(result)
